# Generated by Django 3.2.10 on 2021-12-17 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0002_auto_20211217_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialconcept',
            name='tag',
            field=models.CharField(max_length=255, unique=True, verbose_name='XBRL Tag'),
        ),
    ]
