# Generated by Django 3.2.10 on 2021-12-17 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financials", "0003_alter_financialconcept_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="timedimension",
            name="key",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
