# Generated by Django 3.2.10 on 2021-12-17 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0005_auto_20211217_0506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialfact',
            name='filing',
        ),
        migrations.DeleteModel(
            name='Filing',
        ),
    ]
