# Generated by Django 3.2.10 on 2021-12-17 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0007_auto_20211217_2120'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='financialfact',
            name='unique financial fact',
        ),
        migrations.AddConstraint(
            model_name='financialfact',
            constraint=models.UniqueConstraint(fields=('company', 'concept', 'period', 'value'), name='unique financial fact'),
        ),
    ]
