# Generated by Django 3.2.10 on 2021-12-17 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0008_auto_20211217_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialfact',
            name='value',
            field=models.BigIntegerField(),
        ),
    ]
