# Generated by Django 3.2.10 on 2021-12-17 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financials", "0009_alter_financialfact_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="istracked",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="company",
            name="CIK",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="company",
            name="ticker",
            field=models.CharField(max_length=10),
        ),
    ]
