# Generated by Django 3.2.10 on 2021-12-17 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financials", "0010_auto_20211217_2310"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="ticker",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
