# Generated by Django 3.2.10 on 2021-12-20 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0014_financialfact_filing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='company',
            name='CIK',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='ticker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financials.ticker'),
        ),
    ]
