# Generated by Django 3.2.10 on 2021-12-20 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("financials", "0015_auto_20211220_2045"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="ticker",
        ),
        migrations.AddField(
            model_name="ticker",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickers",
                to="financials.company",
            ),
            preserve_default=False,
        ),
    ]
