# Generated by Django 3.2.10 on 2021-12-22 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0020_auto_20211221_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timedimension',
            name='key',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
