# Generated by Django 3.2.10 on 2021-12-31 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("financials", "0022_auto_20211231_0114"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="financialfact",
            options={"ordering": ["-period__end_date"]},
        ),
    ]
