# Generated by Django 3.2.10 on 2022-01-01 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0023_alter_financialfact_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='fiscal_year_end',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
