# Generated by Django 3.2.10 on 2022-01-01 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financials", "0024_company_fiscal_year_end"),
    ]

    operations = [
        migrations.AddField(
            model_name="financialfact",
            name="type",
            field=models.CharField(
                choices=[("a", "Annual"), ("q", "Quarter")], default="a", max_length=1
            ),
            preserve_default=False,
        ),
    ]
