# Generated by Django 3.2.10 on 2022-01-03 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financials", "0026_financialfact_is_framed"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="financialfact",
            name="unique financial fact",
        ),
        migrations.AddConstraint(
            model_name="financialfact",
            constraint=models.UniqueConstraint(
                fields=("company", "concept", "filing", "period", "value"),
                name="unique financial fact",
            ),
        ),
    ]
